service:
  name: fop

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: ${self:provider.environment.REGION}
  environment:
    REGION: us-east-1
functions:
  getNearestBeaches:
    handler: src/functions/getNearestBeaches.handler
    description: "[${self:provider.stage}] Get a list of nearest beaches"
    events:
      - http:
          method: get
          path: nearestBeaches
          cors: true
  login:
    handler: src/functions/login.handler
    description: "[${self:provider.stage}] Login endpoint that returns the current user"
    events:
      - http:
          method: post
          path: login
          cors: true
  getConversationsByUser:
    handler: src/functions/getConversationsByUser.handler
    description: "[${self:provider.stage}] Get all user's conversations"
    events:
      - http:
          method: get
          path: users/{userId}/conversations
          cors: true

plugins:
  - serverless-webpack
